name: SVCMute
version: '2.2'
main: net.envexus.svcmute.SVCMute
api-version: '1.20'
folia-supported: true
softdepend:
  - Essentials
  - LiteBans
  - AdvancedBan
  - AdvancedBanX
  - PlaceholderAPI
depend:
  - voicechat